# Generated by Django 5.2.10 on 2026-04-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_instructor_approved',
            field=models.BooleanField(default=False, help_text='Whether the instructor account has been approved by an admin'),
        ),
    ]
