# Generated by Django 5.2.10 on 2026-04-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progress_completed_at_alter_progress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='last_timestamp',
            field=models.PositiveIntegerField(default=0, help_text='Video timestamp in seconds for resuming'),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_watched_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
