# Generated by Django 5.2.10 on 2026-04-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_money_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_money_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('vodacom', 'Vodacom M-Pesa'), ('airtel', 'Airtel Money'), ('halotel', 'Halotel Money'), ('ttcl', 'TTCL Money'), ('yas', 'Yas Money')], default='card', max_length=20),
        ),
    ]
