# Generated by Django 5.2.10 on 2026-04-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_mobile_money_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clickpesa_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
