# Generated by Django 5.2.10 on 2026-04-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_clickpesa_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('mpesa', 'M-Pesa'), ('vodacom', 'Vodacom M-Pesa'), ('airtel', 'Airtel Money'), ('tigopesa', 'Tigo Pesa'), ('halotel', 'Halotel Money'), ('ttcl', 'TTCL Money'), ('yas', 'Yas Money')], default='card', max_length=20),
        ),
    ]
